chore: Bump apollo to v4
ThreadsStyling/apollo-resolver-types pull request #40
Opened 2023-07-18 09:46 UTC by danLDev

BREAKING CHANGE

### Remove apollo-server-koa and replace with @apollo/server v4

### Bump graphql to version 16
- Bumped typescript to v5 for compatibility
- Remove tslint in favour of eslint for compatibility with TS v5

### Update examples to use @apollo/server and @apollo/subgraph

2023-07-18 09:59 UTC, diogofcunha commented on src/types/ObjectResolversType.test.ts
> +    // eslint-disable-next-line @typescript-eslint/ban-types
[question] Why is this a rule if we need to suppress it so many times? could we just ignore globally?

2023-07-18 10:02 UTC, diogofcunha requested changes
Overall it looks good, my major concern is that the errors became bound with no context, we may be introducing an issue there.

Could you also talk about the changes from `{}` to `object`? Those are not the same thing

2023-07-18 10:02 UTC, diogofcunha commented on src/__tests__/validateSchema.test.ts
> +    Unknown type \\"Cont\\". Did you mean \\"Int\\"?
[blocking] Any idea why the errors became so less helpful? It almost seems as if the new code is not taking the schema types into context, we probably have a bug here

2023-07-18 10:04 UTC, danLDev commented on src/types/ObjectResolversType.test.ts
> +    // eslint-disable-next-line @typescript-eslint/ban-types
Fair point, will roll back changes and ignore the rule

2023-07-18 10:06 UTC, danLDev commented on src/__tests__/validateSchema.test.ts
> +    Unknown type \\"Cont\\". Did you mean \\"Int\\"?
As above, the changes from `{}` to `object` were linter related, will roll back.

2023-07-18 10:33 UTC, danLDev commented on src/__tests__/validateSchema.test.ts
> +    Unknown type \\"Cont\\". Did you mean \\"Int\\"?
Error messages seem to be a direct result of the bump from graphql 14 -> 16. Error messages are present in 14 but become less helpful in >=15.

Trying to dig a little deeper but there doesn't seem to be any clear migration docs

2023-07-18 10:47 UTC, diogofcunha commented on src/__tests__/validateSchema.test.ts
> +    Unknown type \\"Cont\\". Did you mean \\"Int\\"?
Yeah, let's timebox some exploration on that as these error messages were very helpful

2023-07-18 16:17 UTC, danLDev commented on src/__tests__/validateSchema.test.ts
> +    Unknown type \\"Cont\\". Did you mean \\"Int\\"?
For anyone else looking at this, we discovered that the functionality is still the same, but the suggestion threshold changed in [this commit](https://github.com/graphql/graphql-js/commit/4c10844f6f2ab3e2993d8d5f5f3ed97dce9d3655). Meaning we no longer get suggestions with the current testing criteria.

2023-07-18 16:31 UTC, diogofcunha approved these changes

2023-07-18 16:31 UTC, diogofcunha commented
@danLDev don't forget to change this to feat or it won't publish

2023-07-19 07:48 UTC, merged

2023-07-19 08:52 UTC, techthreads commented
:tada: This PR is included in version 3.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@threads/apollo-resolver-types/v/3.5.0)
- [GitHub release](https://github.com/ThreadsStyling/apollo-resolver-types/releases/tag/v3.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: